Teste1/Teste1/Teste1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/", include("app.urls"))
]

Teste1/Teste1/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("aluno/", views.aluno, name="aluno"),
    path("comecar/", views.comecar, name="comecar"),
    path('comecar/resultado/', views.results, name='results'),
]

Teste1/Teste1/app/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta

class question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    def __str__(self):
        return self.question_text
    def is_old_question(self):
        now = timezone.now()
        return now - self.pub_date > timedelta(days=1)
    
class choice(models.Model):
    votes =  models.IntegerField(default=0)
    question = models.ForeignKey(question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    def __str__(self):
        return self.choice_text

Teste1/Teste1/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import question, choice
from django.template import loader

def index(request):
    template = loader.get_template('app/index.html')
    return render(request, 'app/index.html')

def detail(request):
    return render(request, 'app/detail.html')

def aluno(request):
    return render(request, 'app/aluno.html')

def comecar(request):
    questions = question.objects.all()
    if request.method == 'POST':
        results = {}
        for key in request.POST:
            if key.startswith('result'):
                results[key[6:]] = request.POST[key]
    return render(request, 'app/comecar.html', context={'questions': questions})

def results(request):
    if request.method == 'POST':
        for key, value in request.POST.items():
            print(f'{key}: {value}')
    return render(request, 'app/comecar/resultado.html')

def vote(request, question_id):
    q = get_object_or_404(question, pk=question_id)
    return render(request, 'app/vote.html', {'question': q})

Teste1/Teste1/app/templates/app/aluno.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Aluno</title>
  </head>
  <body>
    <h1>Página do Aluno</h1>
    <p>Bem-vindo à página do Aluno.</p>
  </body>
</html>

Teste1/Teste1/app/templates/app/comecar.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Questions</title>
  </head>
  <body>
    <h1>Test</h1>
    <form method="post" action="{% url 'app:results' %}">
      {% csrf_token %}
      {% for question in questions %}
        <fieldset>
          <legend>{{ question.question_text }}</legend>
          {% for choice in question.choice_set.all %}
            <input type="radio" id="choice{{ choice.id }}" name="question{{ question.id }}" value="{{ choice.id }}" required>
            <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br>
          {% endfor %}
        </fieldset>
      {% endfor %}
      <button type="submit">Submit</button>
    </form>
  </body>
</html>

Teste1/Teste1/app/templates/app/detail.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Teste psicotécnicos</title>
  </head>
  <body>
  </body>
</html>

Teste1/Teste1/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Teste psicotécnicos</title>
  </head>
  <body>
    <p>Menu</p>
    <nav>
      <ul>
        <li><a href="aluno" target="_blank">Aluno</a></li>
        <li><a href="comecar" target="_blank">Começar</a></li>
        <li><a href="sair" target="_blank">Sair</a></li>
      </ul>
    </nav>
  </body>
</html>

Teste1/Teste1/app/templates/app/results.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Respostas</title>
  </head>
  <body>
    <h1>Respostas</h1>
    <table>
      <thead>
        <tr>
          <th>Pergunta</th>
          <th>Escolha do usuário</th>
        </tr>
      </thead>
      <tbody>
        {% for key, value in results.items %}
          <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>